version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5555:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=filaup

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "usuario@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "70:80"
    depends_on:
      - postgres